CREATE TABLE tasks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    description LONGTEXT NOT NULL,
    assignee VARCHAR(30) NOT NULL,
    is_done BOOLEAN DEFAULT 0 NOT NULL,
    deadline_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
) 